In [2]:
import numpy as np;
a=np.full((3,4),222)
print(a)

[[222 222 222 222]
 [222 222 222 222]
 [222 222 222 222]]


In [14]:
a1=np.array([1,2,3,4])
print(a1)
a2=np.arange(4,16,3)
print(a2)
print(a1+a2)

[1 2 3 4]
[ 4  7 10 13]
[ 5  9 13 17]


In [20]:
a1*4

array([ 4,  8, 12, 16])

In [23]:
b=np.power(a1,4)
print(b)

[  1  16  81 256]


In [22]:
a1**4

array([  1,  16,  81, 256], dtype=int32)

In [27]:
print(np.shape(a1))
print(np.shape(a2))
print(a1.ndim)

(4,)
(4,)
1


In [29]:
a = np.arange(6)
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
print(a)
print(a[:])
print(a[2:])
print(a[-2:])


[0 1 2 3 4 5]
[0 1 2 3 4 5]
[2 3 4 5]
[4 5]


In [37]:
a=np.array([[1,2,3,4],
        [5,6,7,8],
          [11,12,13,14]])
print(np.shape(a))
print(np.ndim(a))

(3, 4)
2


In [39]:
x=np.zeros((2,3),dtype=int)
print(x)
y=np.ones((2,3),dtype=int)
print(y)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [42]:
a.flatten('C')#row order

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14])

In [43]:
a.flatten('F')#coloumn order

array([ 1,  5, 11,  2,  6, 12,  3,  7, 13,  4,  8, 14])

In [49]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
a = [[2, 4, 6, 8, 10],
     [3, 6, 9, 12, 15],
     [4, 8, 12, 16, 20]]
print(np.ndim(a))

2
